### ISSUE TITLE
'platform' module conflict with python built-in module

### ISSUE THREAD

**Issue by kcwu** [bdarnell/plop#21]
```
$ cat a.py
import platform
print platform.uname()[0]
$ python a.py
FreeBSD
$ python -m plop.collector a.py
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/local/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/usr/local/lib/python2.7/site-packages/plop/collector.py", line 104, in main
    exec f.read() in globals(), globals()
  File "<string>", line 2, in <module>
AttributeError: 'module' object has no attribute 'uname'
```

This is because collector pass globals() to user script, but `__package__='plop'` too.

**Comment by bdarnell** [comment]
Thanks, I've fixed this.
