### ISSUE TITLE
flamegraph visualization fails

### ISSUE THREAD

**Issue by perrette** [bdarnell/plop#31]
Hi, thanks for the very nice tool!

The standard view works fine, but I am having trouble with `-f flamegraph` option though. The problem can be seen in this simple example:

```python
def func(x):
    for i in xrange(x):
        fibo(i)

def fibo(n):
    if n == 0: return 0
    elif n == 1: return 1
    else: return fibo(n-1)+fibo(n-2)


if __name__ == "__main__":
    func(20)
```

To produce a flame output:

```bash
$ python -m plop.collector -f flamegraph testprofile.py 
profile output saved to profiles/testprofile.py-20170222-1740-59.flame
overhead was 6.49690628052e-05 per sample (0.00649690628052%)
```

the `profiles/testprofile.py-20170222-1740-59.flame` looks like:

```
None 1
_run_module_as_main (/usr/lib/python2.7/runpy.py:147);_run_code (/usr/lib/python2.7/runpy.py:62);<module> (/home/perrette/envs/default/lib/python2.7/site-packages/plop/collector.py:1);main (/home/perrette/envs/default/lib/python2.7/site-packages/plop/collector.py:128);exec_ (/home/perrette/envs/default/local/lib/python2.7/site-packages/six.py:689);<module> (<string>:1);<module> (<string>:1);func (<string>:1);fibo (<string>:5);fibo (<string>:5);fibo (<string>:5);fibo (<string>:5);fibo (<string>:5);fibo (<string>:5);fibo (<string>:5);fibo (<string>:5);fibo (<string>:5);fibo (<string>:5);fibo (<string>:5) 1
_run_module_as_main (/usr/lib/python2.7/runpy.py:147);_run_code (/usr/lib/python2.7/runpy.py:62);<module> (/home/perrette/envs/default/lib/python2.7/site-packages/plop/collector.py:1);main (/home/perrette/envs/default/lib/python2.7/site-packages/plop/collector.py:128);exec_ (/home/perrette/envs/default/local/lib/python2.7/site-packages/six.py:689);<module> (<string>:1);<module> (<string>:1);func (<string>:1);fibo (<string>:5);fibo (<string>:5);fibo (<string>:5);fibo (<string>:5);fibo (<string>:5);fibo (<string>:5);fibo (<string>:5);fibo (<string>:5);fibo (<string>:5);fibo (<string>:5) 1
```

Which yields the following error when run in the server:

```
[I 170222 17:43:19 web:1971] 200 GET /view?filename=testprofile.py-20170222-1740-59.flame (127.0.0.1) 2.11ms
[E 170222 17:43:20 web:1548] Uncaught exception GET /data?filename=testprofile.py-20170222-1740-59.flame (127.0.0.1)
    HTTPServerRequest(protocol='http', host='localhost:8888', method='GET', uri='/data?filename=testprofile.py-20170222-1740-59.flame', version='HTTP/1.1', remote_ip='127.0.0.1', headers={'Accept-Language': 'de-DE,de;q=0.8,en-US;q=0.6,en;q=0.4,fr;q=0.2', 'Accept-Encoding': 'gzip, deflate, sdch, br', 'Host': 'localhost:8888', 'Accept': 'application/json,*/*', 'User-Agent': 'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/55.0.2883.87 Safari/537.36', 'Dnt': '1', 'Connection': 'keep-alive', 'Referer': 'http://localhost:8888/view?filename=testprofile.py-20170222-1740-59.flame'})
    Traceback (most recent call last):
      File "/home/perrette/envs/default/local/lib/python2.7/site-packages/tornado/web.py", line 1467, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "/home/perrette/envs/default/lib/python2.7/site-packages/plop/viewer.py", line 44, in get
        self.write(profile_to_json(self.get_argument('filename')))
      File "/home/perrette/envs/default/lib/python2.7/site-packages/plop/viewer.py", line 50, in profile_to_json
        graph = CallGraph.load(abspath)
      File "/home/perrette/envs/default/local/lib/python2.7/site-packages/plop/callgraph.py", line 87, in load
        data = ast.literal_eval(f.read())
      File "/usr/lib/python2.7/ast.py", line 49, in literal_eval
        node_or_string = parse(node_or_string, mode='eval')
      File "/usr/lib/python2.7/ast.py", line 37, in parse
        return compile(source, filename, mode, PyCF_ONLY_AST)
      File "<unknown>", line 1
        None 1
             ^
    SyntaxError: invalid syntax
[E 170222 17:43:20 web:1971] 500 GET /data?filename=testprofile.py-20170222-1740-59.flame (127.0.0.1) 6.81ms
```

**Comment by bdarnell** [comment]
`plop.viewer` is for the default (force-directed graph) output format. The flamegraph output is designed to be consumed by a third-party flamegraph viewer like https://github.com/brendangregg/FlameGraph
